M48
; DRILL file {KiCad 8.0.6-8.0.6-0~ubuntu22.04.1} date 2024-11-21T18:36:15-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-21T18:36:15-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6-8.0.6-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
%
G90
G05
T1
X60.5Y-120.5
X98.5Y-120.5
T2
X51.6Y-120.4
X60.4Y-111.6
X89.6Y-120.4
X98.4Y-111.6
M30
